---
title: "EFA and CFA"
output: html_document
date: "2025-04-02"
---

#############################################################
################ Explanatory Factor Analysis ################
#############################################################

#please visit this web-page": https://stats.oarc.ucla.edu/spss/seminars/introduction-to-factor-analysis/a-practical-introduction-to-factor-analysis/"
library(foreign) # for Reading SPSS dataset 
library(lavaan)
library(psych) # for explanator factor analysis
dat <- read.spss("https://stats.idre.ucla.edu/wp-content/uploads/2018/05/SAQ.sav",to.data.frame=TRUE, use.value.labels = FALSE)

data1 <- dat[,1:8] #using first 8 survey items
round(cor(data1),3) #correlation matrix
round(cov(data1),3) #variance-covariance matrix

##Performing EPA of One Factor Model

#Principal Component Analysis

#performing one factor model
PCAresult1 <- prcomp(data1, scale. = T)
print(PCAresult1)

pca_result1 <- principal(data1)
print(pca_result1)


print(pca_result2$loadings)

eigenvalues <- result1$e.values
print(eigenvalues)

#calculating eigen vlaues
cor_matrix <- cor(data1)
eigen_result <- eigen(cor_matrix)
eigenvalues <- eigen_result$values
eigenvectors <- eigen_result$vectors
print(eigenvalues)
print(eigenvectors)

#component matrix 
pca_result <- principal(data1, nfactors = ncol(data1), rotate = "none")
print(pca_result$loadings)

#Scree Tree Plot
fa.parallel(data1, fa = "pc", n.iter = 100, show.legend = TRUE, main = "Scree Plot")

#Kaiser Criterion

##Performing PCA of Two Factor Model
#performing two factor model
pca_result2 <- principal(data1, nfactors = 2, rotate = "none")
print(pca_result2)

#component matrix
print(pca_result2$loadings)

#Eingenvalues
eigenvalues2 <- pca_result2$values
print(eigenvalues2)

##Common Factor Analysis with two factor model
cfa_result2 <- fa(data1, nfactors = 2, fm='pa', rotate = "none", max.iter = 100)
print(cfa_result2)

#Rotation Methods with varimax 
cfa_result3 <- fa(data1, nfactors = 2, fm='pa', rotate = "varimax", max.iter = 100)
print(cfa_result3)
rotated_factor_matrix <- cfa_result3$loadings[]
print(rotated_factor_matrix)

#without Kaiser Normalization
cfa_result4 <- fa(data1, nfactors = 2, fm='pa', 
                  rotate = "none", max.iter = 100, normalize = FALSE) #for No Kaiser Normalization
print(cfa_result4)
noNormalrotated_factor_matrix <- cfa_result4$loadings[]
print(noNormalrotated_factor_matrix)

#factor rotation matrix
rotation_matrix <- cfa_result3$rot.mat
print(rotation_matrix)


#Rotation Methods with oblique 
cfa_result4 <- fa(data1, nfactors = 2, fm='pa', rotate = "oblimin", max.iter = 100)
print(cfa_result4)



##############################################################
################ Confirmatory Factor Analysis ################
##############################################################
#Please see this vedio clips before you are doing this
#https://stats.idre.ucla.edu/r/seminars/rcfa/
#install.packages("foreign", dependencies=TRUE)
#install.packages("lavaan", dependencies=TRUE)
library(foreign) # for Reading SPSS dataset 
library(lavaan)


#import data
dat <- read.spss("https://stats.idre.ucla.edu/wp-content/uploads/2018/05/SAQ.sav",to.data.frame=TRUE, use.value.labels = FALSE)

#covariance of Items 3 to 5
round(cov(dat[,3:5]),2) #covariance matrix
round(cor(dat[,3:5]),2) #correlation matrix


#one factor three items, default marker method
m1a  <- ' f  =~ q03 + q04 + q05'
onefac3items_a <- cfa(m1a, data=dat) 
summary(onefac3items_a) 

m1a2  <- ' f  =~ 1*q03 + q04 + q05' #identical with the above syntax
onefac3items_a2 <- cfa(m1a2, data=dat) 
summary(onefac3items_a2) 

m1a3  <- ' f  =~ 1 + q03 + q04 + q05' #calculating intercepts
onefac3items_a3 <- cfa(m1a3, data=dat) 
summary(onefac3items_a3) 

#one factor three items, variance std 
m1b  <- ' f =~ NA*q03 + q04 + q05
          f ~~ 1*f ' 
onefac3items_b <- cfa(m1b, data=dat) 
summary(onefac3items_b)

#alternative model to variance standardization 
onefac3items_a <- cfa(m1a, data=dat,std.lv=TRUE)
summary(onefac3items_a)

#obtain standardized loadings
summary(onefac3items_a,standardized=TRUE)

#alternative condensed standardized solutions
standardizedsolution(onefac3items_a)

#obtain implied variance covariance matrix 
inspect(onefac3items_a,"cov.ov")

#one factor three items, with means 
m1c <- ' f =~ q03 + q04 + q05 
              q03 ~ 1 
              q04 ~ 1 
              q05 ~ 1' 
onefac3items_c <- cfa(m1c, data=dat) 
summary(onefac3items_c)

#error with default two items
m2a <- 'f1 =~ q03 + q04' 
onefac2items <- cfa(m2a, data=dat)
summary(onefac2items)

#one factor, two items (var std) 
m2b <- 'f1 =~ a*q04 + a*q05' 
onefac2items_b <- cfa(m2b, data=dat,std.lv=TRUE) 
summary(onefac2items_b)

#one factor eight items, variance std 
m3a <- 'f =~ q01 + q02 + q03 + q04 + q05 + q06 + q07 + q08' 
onefac8items_a <- cfa(m3a, data=dat,std.lv=TRUE) 
summary(onefac8items_a, fit.measures=TRUE, standardized=TRUE)

#covariance of Items 1 through 8 
round(cor(dat[,1:8]),2)

#fit statistics 
summary(onefac8items_a, fit.measures=TRUE, standardized=TRUE)

#model chi-square 
pchisq(q=554.191,df=20,lower.tail=FALSE)

#baseline model
b1 <- ' q01 ~~ q01 
        q02 ~~ q02 
        q03 ~~ q03 
        q04 ~~ q04 
        q05 ~~ q05 
        q06 ~~ q06 
        q07 ~~ q07 
        q08 ~~ q08' 

basemodel <- cfa(b1, data=dat)
summary(basemodel)

#uncorrelated two factor solution, var std method
m4a <- 'f1 =~ q01+ q03 + q04 + q05 + q08 
        f2 =~ a*q06 + a*q07 
        f1 ~~ 0*f2 ' 
twofac7items_a <- cfa(m4a, data=dat,std.lv=TRUE)

#alternative syntax - uncorrelated two factor solution, var std method
twofac7items_a <- cfa(m4a, data=dat,std.lv=TRUE, auto.cov.lv.x=FALSE) 
summary(twofac7items_a, fit.measures=TRUE,standardized=TRUE)

#uncorrelated two factor solution, marker method
m4b <- 'f1 =~ q01+ q03 + q04 + q05 + q08 
        f2 =~ q06 + q07' 
twofac7items_b <- cfa(m4b, data=dat,std.lv=TRUE) 
summary(twofac7items_b,fit.measures=TRUE,standardized=TRUE)

#second order three factor solution, marker method
m5a <- 'f1 =~ q01+ q03 + q04 + q05 + q08 
        f2 =~ q06 + q07 
        f3 =~ 1*f1 + 1*f2 
        f3 ~~ f3' 
secondorder <- cfa(m5a, data=dat) 
summary(secondorder,fit.measures=TRUE,standardized=TRUE)

#second order three factor solution, var std method
m5b <- 'f1 =~ NA*q01+ q03 + q04 + q05 + q08 
        f2 =~ NA*q06 + q07 
        f3 =~ NA*f1 + equal("f3=~f1")*f2 
        f1 ~~ 1*f1 
        f2 ~~ 1*f2 
        f3 ~~ 1*f3' 
secondorder <- cfa(m5b, data=dat) 
summary(secondorder,fit.measures=TRUE)

#obtain the parameter table of the second order factor
inspect(secondorder,"partable")


#Exercises based on PowerPoint
#5/17/2021
#load libraries
library(foreign) 
library(lavaan)

#import data
dat <- read.spss("https://stats.idre.ucla.edu/wp-content/uploads/2018/05/SAQ.sav",to.data.frame=TRUE, use.value.labels = FALSE)

#exercise 1
#one factor eight items, variance std 
m1 <- 'f =~ q01 + q02 + q03 + q04 + q05 + q06 + q07 + q08' 
onefac8items_a <- cfa(m1, data=dat) 
summary(onefac8items_a,fit.measures=TRUE,standardized=TRUE)

#exercise 2
#correlated two factor solution, marker method
m2 <- 'f1 =~ q01+ q02 + q03 + q04 
        f2 =~ q05 + q06 + q07 + q08' 
twofac8items_a <- cfa(m2, data=dat) 
summary(twofac8items_a,fit.measures=TRUE,standardized=TRUE)

#remove lowest loadings
m3 <- 'f1 =~ q01+ q03 + q04 
        f2 =~ q05 + q06 + q07' 
twofac8items_b <- cfa(m3, data=dat) 
summary(twofac8items_b,fit.measures=TRUE,standardized=TRUE)

#uncorrelated two factor solution, var std method
m4 <- 'f1 =~ q01+ q03 + q04 
        f2 =~ q05 + q06 + q07
        f1 ~~ 0*f2' 
twofac8items_c <- cfa(m4, data=dat) 
summary(twofac8items_c,fit.measures=TRUE,standardized=TRUE)

#exercise 3
#baseline model
b1 <- ' q01 ~~ q01 
        q02 ~~ q02 
        q03 ~~ q03 
        q04 ~~ q04 
        q05 ~~ q05 
        q06 ~~ q06 
        q07 ~~ q07 
        q08 ~~ q08' 

basemodel <- cfa(b1, data=dat)
summary(basemodel)

#saturated model
s1 <- ' q01 ~~ q01 
        q02 ~~ q02 
        q03 ~~ q03 
        q04 ~~ q04 
        q05 ~~ q05 
        q06 ~~ q06 
        q07 ~~ q07 
        q08 ~~ q08
#covariances
        q01 ~~ q02 + q03 + q04 + q05 + q06 + q07 + q08
        q02 ~~       q03 + q04 + q05 + q06 + q07 + q08
        q03 ~~             q04 + q05 + q06 + q07 + q08
        q04 ~~                   q05 + q06 + q07 + q08
        q05 ~~                         q06 + q07 + q08
        q06 ~~                               q07 + q08
        q07 ~~                                     q08
' 

satmodel <- cfa(s1, data=dat)
summary(satmodel)
